name: testing

on:
  push:
    branches:
      - master
      - 'dev/**'

jobs:
  project-build:
    runs-on: ubuntu-latest

    name: Run unit tests on Java 17

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -f pom.xml test

